name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on:
  push:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to run against'
        type: environment
        required: false 

jobs:
  check-go-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3.5.0
        with:
          go-version: '1.19'
      - run: go version

  issue-ssl-certificate:
    name: Issue SSL certificate
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment || 'staging' }}
    container:
      image: neilpang/acme.sh
      env:
        NODE_ENV: development
        SECRET_HOSTS: ${{ secrets.HOSTS }}
      volumes:
        - $GITHUB_WORKSPACE:/acme.sh

    steps:
      - run: |
          acme.sh --help
      - run: |
          for h in $SECRET_HOSTS
          do
            echo "h is $h"
            echo "::add-mask::$h"
            echo "after mask, h is $h"
          done
          echo "HOSTS: $SECRET_HOSTS"
          echo "HOSTS: $SECRET_HOSTS | sed 's/\./#/g'"
          
        shell: bash
        env:
          SECRET_HOSTS: ${{ secrets.HOSTS }}
      
