name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - run: npm install -g bats
      - run: bats -v
      
      - uses: actions/setup-go@v3.5.0
        with:
          go-version: '1.19'
      - run: go version
  issue-ssl-certificate:
    name: Issue SSL certificate
    runs-on: ubuntu-latest
    steps:
      - uses: Menci/acme@v1
        with:
          version: 3.0.2

          # Register your account and try issue a certificate with DNS API mode
          # Then fill with the output of `tar cz ca account.conf | base64 -w0` running in your `~/.acme.sh`
          account-tar: ${{ secrets.ACME_SH_ACCOUNT_TAR }}

          domains: '*.serenitytune.tk *.ddns.serenitytune.tk'
          domains-file: ''
          append-wildcard: false

          arguments: --keylength ec-256 --challenge-alias whisperwind.cf --dns dns_he
          arguments-file: ''

          output-fullchain: '' 
          output-key: '' 
          output-pfx: '' 
          output-pfx-password: ''

          # uninstall: true # Uninstall acme.sh after this action by default
