name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on:
  push:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to run against'
        type: environment
        required: false

jobs:
  check-go-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3.5.0
        with:
          go-version: '1.19'
      - run: go version

  issue-cert:
    name: Issue SSL certificate
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment || 'staging' }}
    container:
      image: neilpang/acme.sh
      env:
        NODE_ENV: development
        SECRET_HOSTS: ${{ secrets.HOSTS }}

    steps:
      - name: acme.sh
        run: |
          DOMAINS=$(echo $ACME_SH_COMMANDS | jq -r ".issue_args" | tr "$IFS" "\n" | sed 's/^"//g; s/"$//g' | grep -Eo "\w+\.\w+$" | sort -u)
          for DOMAIN in $DOMAINS
          do
            echo "::add-mask::$DOMAIN"
          done

          echo "$ACME_SH_ACCOUNT_TAR" | base64 -d | tar -C $LE_CONFIG_HOME -xz

          echo $(echo $ACME_SH_COMMANDS | jq -r ".issue_args")
          echo $(echo $ACME_SH_COMMANDS | jq -r ".install_args")

          acme.sh --issue $(echo $ACME_SH_COMMANDS | jq -r ".issue_args")
          acme.sh --install-cert $(echo $ACME_SH_COMMANDS | jq -r ".install_args") --key-file $GITHUB_WORKSPACE/key.key --fullchain-file $GITHUB_WORKSPACE/cert.crt
        env:
          ACME_SH_ACCOUNT_TAR: ${{ secrets.ACME_SH_ACCOUNT_TAR }}
          ACME_SH_COMMANDS: ${{ secrets.ACME_SH_COMMANDS }}

      - name: inspect
        run: |
          echo "HOSTS: $SECRET_HOSTS"
          echo "HOSTS: $SECRET_HOSTS" | sed 's/\./#/g'

        env:
          SECRET_HOSTS: ${{ secrets.HOSTS }}

      - name: output
        run: |
          echo "ACME_SH_KEY<<EOF" >> $GITHUB_OUTPUT
          cat $GITHUB_WORKSPACE/key.key >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

          echo "ACME_SH_CERT<<EOF" >> $GITHUB_OUTPUT
          cat $GITHUB_WORKSPACE/cert.crt >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

  deploy-cert:
    name: deploy SSL certificate
    needs: issue-cert
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment || 'staging' }}
    container:
      image: alpine
      env:
        NODE_ENV: development
        SECRET_HOSTS: ${{ secrets.HOSTS }}
    steps:
      - run: |
          echo "KEY:"
          echo ${{needs.issue-cert.outputs.ACME_SH_KEY}}
          echo ${{needs.issue-cert.outputs.ACME_SH_KEY}} >$GITHUB_WORKSPACE/key.key
          echo "CERT:"
          echo ${{needs.issue-cert.outputs.ACME_SH_CERT}}
          echo ${{needs.issue-cert.outputs.ACME_SH_CERT}} >$GITHUB_WORKSPACE/cert.crt

