name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on:
  push
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to run against'
        type: environment
        required: false 
        default: staging
        
  check-go-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3.5.0
        with:
          go-version: '1.19'
      - run: go version

  issue-ssl-certificate:
    name: Issue SSL certificate
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - uses: Menci/acme@v1
        if: ${{ false  }}
        with:
          version: 3.0.2

          # Register your account and try issue a certificate with DNS API mode
          # Then fill with the output of `tar cz ca account.conf | base64 -w0` running in your `~/.acme.sh`
          account-tar: ${{ secrets.ACME_SH_ACCOUNT_TAR }}

          domains: '*.serenitytune.tk *.ddns.serenitytune.tk'
          domains-file: ''
          append-wildcard: false

          arguments: --challenge-alias whisperwind.cf --dns dns_he
          arguments-file: ''

          output-fullchain: '' 
          output-key: '' 
          output-pfx: '' 
          output-pfx-password: ''

          uninstall: false
      
      - run: |
          #~/.acme.sh/acme.sh --install-cert -d "$ACME_SH_FIRST_DOMAIN" --fullchain-file "$GITHUB_WORKSPACE/fullchain.pem" --key-file "$GITHUB_WORKSPACE/key.pem"
          for x in 123 ABC XYZ
          do
            echo "x is $x"
            echo "::add-mask::$x"
            echo "after mask, x is $x"
          done
          echo "secrets HOSTS is $SECRET_HOSTS"
        shell: bash
        env:
          SECRET_HOSTS: ${{ secrets.HOSTS }}
      
      - name: Deploy
        uses: alinz/ssh-scp-action@master
        if: ${{ false  }}
        env:
          HELLO: cool
          MESSAGE: hello world
        with:
          key: ${{ secrets.SSH_KEY }}
          host: cc-vps-1.serenitytune.tk
          port: 22
          user: root

          ssh_before: |
            hostname
            date
            ls -lath /etc/v2ray

          scp: |
            #$GITHUB_WORKSPACE/key.pem          root@cc-vps-1.serenitytune.tk:/etc/v2ray
            #$GITHUB_WORKSPACE/fullchain.pem    root@cc-vps-1.serenitytune.tk:/etc/v2ray
            $GITHUB_WORKSPACE/GITHUB_ENV        root@cc-vps-1.serenitytune.tk:/etc/v2ray

          # then run these commands
          ssh_after: |
            hostname
            date
            ls -lath /etc/v2ray
